packages:
  - 'apps/*'
  - 'libs/*'
  - 'apps/customer/*'
  - 'libs/customer/auth/*'
  - 'libs/customer/themes/*'
  - 'libs/customer/profile/*'
  - 'lib/customer/common/*'
  - 'libs/customer/common/*'
